### ISSUE TITLE
Не появляются репозитории

### ISSUE THREAD

**Issue by harddiegg** [badoo/codeisok#36]
Создал в докере образ, подключился по вебу, создал репозиторий(а так же пытался копировать уже существующие репозитории в codeisok/repositories).
Проблема в том, что они не отображаются в вебе ни через минуту, ни через час.
Так же при запуске докер образа наблюдаю такую ошибку: 

> ERROR 1006 (HY000) at line 1: Can't create database 'gitphp' (errno: 13)

Возможно это связано

**Comment by hu11down** [comment]
Репозитории должны появляться сразу. Судя по ошибке, что-то с базой данных. Вероятно, у пользователя не хватает прав для создания базы и необходимых таблиц. 
Проверьте права пользователя mysql пожалуйста.

**Comment by harddiegg** [comment]
В докере авторизуется под пользователем root. Как у него может не хватать прав на создание базы данных?

**Comment by hu11down** [comment]
Ну вы же ничего не написали про то, меняли ли какие-то настройки или нет :)
Тогда мне нужно вот что: платформа, на которой вы пытаетесь запустить докер-контейнер, логи создания образа и логи старта.

**Comment by harddiegg** [comment]
Это да, моя ошибка)
Так, пишу еще раз все сначала)

На чистую поставил контейнер, без каких-либо изменений, запуская, вижу такие логи

> ╰─$ sudo ./start.sh
>  * Starting MySQL database server mysqld                                                                                                                                                                             No directory, logging in with HOME=/
>                                                                                                                                                                                                               [ OK ]
>  * Checking for tables which need an upgrade, are corrupt or were
> not closed cleanly.
>  * Starting OpenBSD Secure Shell server sshd                                                                                                                                                                  [ OK ]
> Warning: Using a password on the command line interface can be insecure.
> ERROR 1006 (HY000) at line 1: Can't create database 'gitphp' (errno: 13)
>  * Starting Mail Transport Agent (MTA) sendmail                                                                                                                                                               [ OK ]
> root@75ae7345e57c:/#
> 

С логами создания сложнее, сейчас нет быстрого канала, не смогу скачать все это(но если это обязательно, то сделаю)

Платформа: Linux 4.16.3-1-ARCH x86_64 GNU/Linux

**Comment by hu11down** [comment]
Спасибо за логи старта. Но логи создания нужны тоже. Судя по тому, что mysql не может найти директорий с данными, что-то пошло не так.
Сделайте пожалуйста, как будет возможность.

Спасибо!

**Comment by harddiegg** [comment]
Удалось получить лог)
https://pastebin.com/J87vYZUZ

**Comment by hu11down** [comment]
А зачем вы docker build запускаете под sudo? Не помню чтобы я в документации указывал что-то подобное. Попробуйте пересоздать контейнер, предварительно удалив то что уже создано ранее и создать по новой, уже без sudo.
Спасибо.

**Comment by harddiegg** [comment]
Запускал сборку под sudo по причине того, что без sudo docker вообще не выполняет никаких команд

> ╰─$ docker build -t codeisok .setup
> Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.37/build?buildargs=%7B%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&session=f54525d0a6653d9ddfd969771cd335680a6eb7d6555d63f3eeb521311bed0f9f&shmsize=0&t=codeisok&target=&ulimits=null: dial unix /var/run/docker.sock: connect: permission denied

> ╰─$ docker images                                                                                                                                                                                                
> Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.37/images/json: dial unix /var/run/docker.sock: connect: permission denied

**Comment by harddiegg** [comment]
Изменил владельца файлов, ошибка изменилась, но опять с базой данных все связано

> ╰─$ sudo ./start.sh                                                                                                                                                                                            
>  * Starting MySQL database server mysqld                                        No directory, logging in with HOME=/
>                                                                          [fail]
>  * Starting OpenBSD Secure Shell server sshd                                                                                                                                                                  [ OK ]
> Warning: Using a password on the command line interface can be insecure.
> ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
>  * Starting Mail Transport Agent (MTA) sendmail                                                                                                                                                               [ OK ]
> root@f40004e0ef4a:/# ls -al /var/run/mysqld/
> total 12
> drwxr-xr-x 2 mysql root 4096 May 15 12:13 .
> drwxr-xr-x 1 root  root 4096 May 15 12:20 ..
> root@f40004e0ef4a:/#

**Comment by hu11down** [comment]
Ну значит у юзера под которым вы работаете в линукс нет прав для работы с докером. 
Надо разобраться с правами и пересоздать образ.

С другой стороны, возможно, команда docker start (которая внутри ./start.sh), будучи запущена под sudo, спасет ситуацию.

**Comment by harddiegg** [comment]
Попытался создать образ и запустить полностью под root, ситуация не изменилась

**Comment by Md-Cake** [comment]
@harddiegg кажется, я нашел и воспроизвел вашу проблему у себя на виртуалке. Я приложил фикс в мастер, можете попробовать пересобрать и запустить контейнер с новыми изменениями?

**Comment by harddiegg** [comment]
Да, фикс действительно помог) Спасибо)
