### ISSUE TITLE
Auto line-breaks for long lines in comments

### ISSUE THREAD

**Issue by zaytsev-mxm** [badoo/codeisok#73]
When you are typing some really long line of text without "manual" line-breaks — it is "overflowing". I think we can add support of "automatic" line-breaks here in CodeIsOK — as it works in native browser textareas.

Actual behaviour: https://yadi.sk/i/XAl3EeVAbySIuw
Expected behaviour: https://yadi.sk/i/-n1ZNnhWYfyfXA

**Comment by makinfieva** [comment]
Fixed - [add line breaks in review comments #95](https://github.com/badoo/codeisok/commit/0a744a8f51ff4ee881683dd181f3deb276225d19)
