### ISSUE TITLE
Add support of code snippets in comments

### ISSUE THREAD

**Issue by zaytsev-mxm** [badoo/codeisok#74]
We miss the support of code formatting in comments. I propose to add support of using of back-slashes for highlighting code snippets — e.g. like it is implemented in Slack – single back-quotes (`) for one-line code-snippets and three back-quotes (```) for multi-line code snippets.

**Comment by hu11down** [comment]
No. We don't need to have code blocks formatting in codeisok.

**Comment by zaytsev-mxm** [comment]
@uyga sorry — why do you think so?
1. It is a really useful thing when you are commenting on someone's code — to provide your own comment with a small illustration
2. It is a common feature in all code-review tools I've ever seen — GitHub, Bitbucket, GitLab etc.

**Comment by hu11down** [comment]
The answer is in my article [here](https://habr.com/ru/company/badoo/blog/413965/)

**Comment by zaytsev-mxm** [comment]
@uyga sorry, but it is not clear how the support of code highlighting may turn the code-review tool into something like a personal blog, messenger or an educational service — as you said in your article. Minimalism is a good thing — but sometimes it is not the only excuse for keeping thing as is. Developers will do not stop using code snippets in their comments even if we are not supporting a handy UI for that — so I don't see any reasons why you closed this issue.
Again — I agree with your position about the role which code-review tool should do — but I do not agree with the statement that adding of code highlighting may change that role.
